-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dw.dim_cliente
(
    id_cliente bigserial NOT NULL,
    documento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default",
    nome_fantasia character varying(255) COLLATE pg_catalog."default",
    municipio character varying(100) COLLATE pg_catalog."default",
    uf character(2) COLLATE pg_catalog."default",
    bairro character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT dim_cliente_pkey PRIMARY KEY (id_cliente),
    CONSTRAINT uq_dim_cliente_doc UNIQUE (documento)
);

CREATE TABLE IF NOT EXISTS dw.dim_fornecedor
(
    id_fornecedor bigserial NOT NULL,
    documento character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default",
    nome_fantasia character varying(255) COLLATE pg_catalog."default",
    municipio character varying(100) COLLATE pg_catalog."default",
    uf character(2) COLLATE pg_catalog."default",
    bairro character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT dim_fornecedor_pkey PRIMARY KEY (id_fornecedor),
    CONSTRAINT uq_dim_fornecedor_doc UNIQUE (documento)
);

CREATE TABLE IF NOT EXISTS dw.dim_produto
(
    id_produto bigserial NOT NULL,
    codigo_produto character varying(60) COLLATE pg_catalog."default" NOT NULL,
    descricao_produto character varying(255) COLLATE pg_catalog."default",
    ncm character varying(8) COLLATE pg_catalog."default",
    cest character varying(7) COLLATE pg_catalog."default",
    codigo_barras character varying(30) COLLATE pg_catalog."default",
    unidade_comercial character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT dim_produto_pkey PRIMARY KEY (id_produto),
    CONSTRAINT uq_dim_produto_codigo UNIQUE (codigo_produto)
);

CREATE TABLE IF NOT EXISTS dw.dim_tempo
(
    id_tempo bigserial NOT NULL,
    data date NOT NULL,
    dia smallint NOT NULL,
    mes smallint NOT NULL,
    nome_mes character varying(20) COLLATE pg_catalog."default" NOT NULL,
    trimestre smallint NOT NULL,
    ano smallint NOT NULL,
    dia_semana character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_tempo_pkey PRIMARY KEY (id_tempo)
);

CREATE TABLE IF NOT EXISTS dw.fato_compra
(
    id_compra bigserial NOT NULL,
    id_tempo integer NOT NULL,
    id_produto bigint NOT NULL,
    id_fornecedor bigint NOT NULL,
    numero_nota character varying(20) COLLATE pg_catalog."default" NOT NULL,
    numero_item integer NOT NULL,
    quantidade numeric(15, 4) NOT NULL,
    valor_unitario numeric(15, 6) NOT NULL,
    valor_produto numeric(15, 2) NOT NULL,
    CONSTRAINT fato_compra_pkey PRIMARY KEY (id_compra),
    CONSTRAINT uq_fato_compra_nota_item UNIQUE (numero_nota, numero_item, id_fornecedor)
);

CREATE TABLE IF NOT EXISTS dw.fato_venda
(
    id_venda bigserial NOT NULL,
    id_tempo integer NOT NULL,
    id_produto bigint NOT NULL,
    id_cliente bigint NOT NULL,
    numero_nota character varying(20) COLLATE pg_catalog."default" NOT NULL,
    numero_item integer NOT NULL,
    quantidade numeric(15, 4) NOT NULL,
    valor_unitario numeric(15, 6) NOT NULL,
    valor_produto numeric(15, 2) NOT NULL,
    CONSTRAINT fato_venda_pkey PRIMARY KEY (id_venda),
    CONSTRAINT uq_fato_venda_nota_item UNIQUE (numero_nota, numero_item, id_cliente)
);

ALTER TABLE IF EXISTS dw.fato_compra
    ADD CONSTRAINT fato_compra_id_fornecedor_fkey FOREIGN KEY (id_fornecedor)
    REFERENCES dw.dim_fornecedor (id_fornecedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_fato_compra_fornecedor
    ON dw.fato_compra(id_fornecedor);


ALTER TABLE IF EXISTS dw.fato_compra
    ADD CONSTRAINT fato_compra_id_produto_fkey FOREIGN KEY (id_produto)
    REFERENCES dw.dim_produto (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_fato_compra_produto
    ON dw.fato_compra(id_produto);


ALTER TABLE IF EXISTS dw.fato_compra
    ADD CONSTRAINT fato_compra_id_tempo_fkey FOREIGN KEY (id_tempo)
    REFERENCES dw.dim_tempo (id_tempo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_fato_compra_tempo
    ON dw.fato_compra(id_tempo);


ALTER TABLE IF EXISTS dw.fato_venda
    ADD CONSTRAINT fato_venda_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES dw.dim_cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_fato_venda_cliente
    ON dw.fato_venda(id_cliente);


ALTER TABLE IF EXISTS dw.fato_venda
    ADD CONSTRAINT fato_venda_id_produto_fkey FOREIGN KEY (id_produto)
    REFERENCES dw.dim_produto (id_produto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_fato_venda_produto
    ON dw.fato_venda(id_produto);


ALTER TABLE IF EXISTS dw.fato_venda
    ADD CONSTRAINT fato_venda_id_tempo_fkey FOREIGN KEY (id_tempo)
    REFERENCES dw.dim_tempo (id_tempo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ix_fato_venda_tempo
    ON dw.fato_venda(id_tempo);

END;